// ── locations/bt.js ─────────────────────────────────────────────
// Scene data for: Cawangan Daerah Seberang Perai Utara
// ────────────────────────────────────────────────────────────────

export default [
  {
    id: 'bt-ext-outside-1',
    name: 'Exterior – Outside 1',
    caption: 'BT – Exterior – Outside 1',
    panorama: './images/bt/bt-ext-outside-1.jpg',
    thumbnail: './images/bt/bt-ext-outside-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
      {
        nodeId: 'bt-ext-outside-2',
        position: { yaw: '358.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 2',
      },
    ],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-2',
    name: 'Exterior – Outside 2',
    caption: 'BT – Exterior – Outside 2',
    panorama: './images/bt/bt-ext-outside-2.jpg',
    thumbnail: './images/bt/bt-ext-outside-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-3',
    name: 'Exterior – Outside 3',
    caption: 'BT – Exterior – Outside 3',
    panorama: './images/bt/bt-ext-outside-3.jpg',
    thumbnail: './images/bt/bt-ext-outside-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-4',
    name: 'Exterior – Outside 4',
    caption: 'BT – Exterior – Outside 4',
    panorama: './images/bt/bt-ext-outside-4.jpg',
    thumbnail: './images/bt/bt-ext-outside-4.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-5',
    name: 'Exterior – Outside 5',
    caption: 'BT – Exterior – Outside 5',
    panorama: './images/bt/bt-ext-outside-5.jpg',
    thumbnail: './images/bt/bt-ext-outside-5.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-f1-lobby-1',
    name: 'Floor 1 – Lobby 1',
    caption: 'BT – Floor 1 – Lobby 1',
    panorama: './images/bt/bt-f1-lobby-1.jpg',
    thumbnail: './images/bt/bt-f1-lobby-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['lobby'],
    },
  },
  {
    id: 'bt-f1-lobby-2',
    name: 'Floor 1 – Lobby 2',
    caption: 'BT – Floor 1 – Lobby 2',
    panorama: './images/bt/bt-f1-lobby-2.jpg',
    thumbnail: './images/bt/bt-f1-lobby-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['lobby'],
    },
  },
  {
    id: 'bt-f1-lobby-3',
    name: 'Floor 1 – Lobby 3',
    caption: 'BT – Floor 1 – Lobby 3',
    panorama: './images/bt/bt-f1-lobby-3.jpg',
    thumbnail: './images/bt/bt-f1-lobby-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['lobby'],
    },
  },
  {
    id: 'bt-f1-kids-1',
    name: 'Floor 1 – Kids 1',
    caption: 'BT – Floor 1 – Kids 1',
    panorama: './images/bt/bt-f1-kids-1.jpg',
    thumbnail: './images/bt/bt-f1-kids-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-2',
    name: 'Floor 1 – Kids 2',
    caption: 'BT – Floor 1 – Kids 2',
    panorama: './images/bt/bt-f1-kids-2.jpg',
    thumbnail: './images/bt/bt-f1-kids-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-3',
    name: 'Floor 1 – Kids 3',
    caption: 'BT – Floor 1 – Kids 3',
    panorama: './images/bt/bt-f1-kids-3.jpg',
    thumbnail: './images/bt/bt-f1-kids-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-4',
    name: 'Floor 1 – Kids 4',
    caption: 'BT – Floor 1 – Kids 4',
    panorama: './images/bt/bt-f1-kids-4.jpg',
    thumbnail: './images/bt/bt-f1-kids-4.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-5',
    name: 'Floor 1 – Kids 5',
    caption: 'BT – Floor 1 – Kids 5',
    panorama: './images/bt/bt-f1-kids-5.jpg',
    thumbnail: './images/bt/bt-f1-kids-5.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-6',
    name: 'Floor 1 – Kids 6',
    caption: 'BT – Floor 1 – Kids 6',
    panorama: './images/bt/bt-f1-kids-6.jpg',
    thumbnail: './images/bt/bt-f1-kids-6.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-7',
    name: 'Floor 1 – Kids 7',
    caption: 'BT – Floor 1 – Kids 7',
    panorama: './images/bt/bt-f1-kids-7.jpg',
    thumbnail: './images/bt/bt-f1-kids-7.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-8',
    name: 'Floor 1 – Kids 8',
    caption: 'BT – Floor 1 – Kids 8',
    panorama: './images/bt/bt-f1-kids-8.jpg',
    thumbnail: './images/bt/bt-f1-kids-8.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
];
