// ── locations/bt.js ─────────────────────────────────────────────
// Scene data for: Cawangan Daerah Seberang Perai Utara
// ────────────────────────────────────────────────────────────────

export default [
  {
    id: 'bt-ext-outside-1',
    name: 'Exterior – Outside 1',
    caption: 'BT – Exterior – Outside 1',
    panorama: './images/bt/bt-ext-outside-1.jpg',
    thumbnail: './images/bt/bt-ext-outside-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
      {
        nodeId: 'bt-ext-outside-2',
        position: { yaw: '358.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 2',
      },
    ],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-2',
    name: 'Exterior – Outside 2',
    caption: 'BT – Exterior – Outside 2',
    panorama: './images/bt/bt-ext-outside-2.jpg',
    thumbnail: './images/bt/bt-ext-outside-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
      {
        nodeId: 'bt-ext-outside-1',
        position: { yaw: '178.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 1',
      },
      {
        nodeId: 'bt-ext-outside-3',
        position: { yaw: '358.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 3',
      },
    ],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-3',
    name: 'Exterior – Outside 3',
    caption: 'BT – Exterior – Outside 3',
    panorama: './images/bt/bt-ext-outside-3.jpg',
    thumbnail: './images/bt/bt-ext-outside-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
      {
        nodeId: 'bt-ext-outside-2',
        position: { yaw: '178.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 2',
      },
      {
        nodeId: 'bt-ext-outside-4',
        position: { yaw: '358.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 4',
      },
    ],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-4',
    name: 'Exterior – Outside 4',
    caption: 'BT – Exterior – Outside 4',
    panorama: './images/bt/bt-ext-outside-4.jpg',
    thumbnail: './images/bt/bt-ext-outside-4.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
      {
        nodeId: 'bt-ext-outside-3',
        position: { yaw: '178.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 3',
      },
      {
        nodeId: 'bt-ext-outside-5',
        position: { yaw: '358.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 5',
      },
    ],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-ext-outside-5',
    name: 'Exterior – Outside 5',
    caption: 'BT – Exterior – Outside 5',
    panorama: './images/bt/bt-ext-outside-5.jpg',
    thumbnail: './images/bt/bt-ext-outside-5.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
      {
        nodeId: 'bt-ext-outside-4',
        position: { yaw: '178.45deg', pitch: '-8.15deg' },
        name: 'Go to Outside 4',
      },
    ],
    markers: [],
    data: {
      floor: 'ext',
      tags: ['exterior', 'outside'],
    },
  },
  {
    id: 'bt-f1-lobby-1',
    name: 'Floor 1 – Lobby 1',
    caption: 'BT – Floor 1 – Lobby 1',
    panorama: './images/bt/bt-f1-lobby-1.jpg',
    thumbnail: './images/bt/bt-f1-lobby-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['lobby'],
    },
  },
  {
    id: 'bt-f1-lobby-2',
    name: 'Floor 1 – Lobby 2',
    caption: 'BT – Floor 1 – Lobby 2',
    panorama: './images/bt/bt-f1-lobby-2.jpg',
    thumbnail: './images/bt/bt-f1-lobby-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['lobby'],
    },
  },
  {
    id: 'bt-f1-lobby-3',
    name: 'Floor 1 – Lobby 3',
    caption: 'BT – Floor 1 – Lobby 3',
    panorama: './images/bt/bt-f1-lobby-3.jpg',
    thumbnail: './images/bt/bt-f1-lobby-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['lobby'],
    },
  },
  {
    id: 'bt-f1-kids-1',
    name: 'Floor 1 – Kids 1',
    caption: 'BT – Floor 1 – Kids 1',
    panorama: './images/bt/bt-f1-kids-1.jpg',
    thumbnail: './images/bt/bt-f1-kids-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-2',
    name: 'Floor 1 – Kids 2',
    caption: 'BT – Floor 1 – Kids 2',
    panorama: './images/bt/bt-f1-kids-2.jpg',
    thumbnail: './images/bt/bt-f1-kids-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-3',
    name: 'Floor 1 – Kids 3',
    caption: 'BT – Floor 1 – Kids 3',
    panorama: './images/bt/bt-f1-kids-3.jpg',
    thumbnail: './images/bt/bt-f1-kids-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-4',
    name: 'Floor 1 – Kids 4',
    caption: 'BT – Floor 1 – Kids 4',
    panorama: './images/bt/bt-f1-kids-4.jpg',
    thumbnail: './images/bt/bt-f1-kids-4.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-5',
    name: 'Floor 1 – Kids 5',
    caption: 'BT – Floor 1 – Kids 5',
    panorama: './images/bt/bt-f1-kids-5.jpg',
    thumbnail: './images/bt/bt-f1-kids-5.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-6',
    name: 'Floor 1 – Kids 6',
    caption: 'BT – Floor 1 – Kids 6',
    panorama: './images/bt/bt-f1-kids-6.jpg',
    thumbnail: './images/bt/bt-f1-kids-6.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-7',
    name: 'Floor 1 – Kids 7',
    caption: 'BT – Floor 1 – Kids 7',
    panorama: './images/bt/bt-f1-kids-7.jpg',
    thumbnail: './images/bt/bt-f1-kids-7.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-kids-8',
    name: 'Floor 1 – Kids 8',
    caption: 'BT – Floor 1 – Kids 8',
    panorama: './images/bt/bt-f1-kids-8.jpg',
    thumbnail: './images/bt/bt-f1-kids-8.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['kids'],
    },
  },
  {
    id: 'bt-f1-tyt-1',
    name: 'Floor 1 – TYT 1',
    caption: 'BT – Floor 1 – TYT 1',
    panorama: './images/bt/bt-f1-tyt-1.jpg',
    thumbnail: './images/bt/bt-f1-tyt-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-2',
    name: 'Floor 1 – TYT 2',
    caption: 'BT – Floor 1 – TYT 2',
    panorama: './images/bt/bt-f1-tyt-2.jpg',
    thumbnail: './images/bt/bt-f1-tyt-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-3',
    name: 'Floor 1 – TYT 3',
    caption: 'BT – Floor 1 – TYT 3',
    panorama: './images/bt/bt-f1-tyt-3.jpg',
    thumbnail: './images/bt/bt-f1-tyt-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-4',
    name: 'Floor 1 – TYT 4',
    caption: 'BT – Floor 1 – TYT 4',
    panorama: './images/bt/bt-f1-tyt-4.jpg',
    thumbnail: './images/bt/bt-f1-tyt-4.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-5',
    name: 'Floor 1 – TYT 5',
    caption: 'BT – Floor 1 – TYT 5',
    panorama: './images/bt/bt-f1-tyt-5.jpg',
    thumbnail: './images/bt/bt-f1-tyt-5.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-6',
    name: 'Floor 1 – TYT 6',
    caption: 'BT – Floor 1 – TYT 6',
    panorama: './images/bt/bt-f1-tyt-6.jpg',
    thumbnail: './images/bt/bt-f1-tyt-6.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-7',
    name: 'Floor 1 – TYT 7',
    caption: 'BT – Floor 1 – TYT 7',
    panorama: './images/bt/bt-f1-tyt-7.jpg',
    thumbnail: './images/bt/bt-f1-tyt-7.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-8',
    name: 'Floor 1 – TYT 8',
    caption: 'BT – Floor 1 – TYT 8',
    panorama: './images/bt/bt-f1-tyt-8.jpg',
    thumbnail: './images/bt/bt-f1-tyt-8.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-9',
    name: 'Floor 1 – TYT 9',
    caption: 'BT – Floor 1 – TYT 9',
    panorama: './images/bt/bt-f1-tyt-9.jpg',
    thumbnail: './images/bt/bt-f1-tyt-9.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-10',
    name: 'Floor 1 – TYT 10',
    caption: 'BT – Floor 1 – TYT 10',
    panorama: './images/bt/bt-f1-tyt-10.jpg',
    thumbnail: './images/bt/bt-f1-tyt-10.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-11',
    name: 'Floor 1 – TYT 11',
    caption: 'BT – Floor 1 – TYT 11',
    panorama: './images/bt/bt-f1-tyt-11.jpg',
    thumbnail: './images/bt/bt-f1-tyt-11.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-12',
    name: 'Floor 1 – TYT 12',
    caption: 'BT – Floor 1 – TYT 12',
    panorama: './images/bt/bt-f1-tyt-12.jpg',
    thumbnail: './images/bt/bt-f1-tyt-12.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-13',
    name: 'Floor 1 – TYT 13',
    caption: 'BT – Floor 1 – TYT 13',
    panorama: './images/bt/bt-f1-tyt-13.jpg',
    thumbnail: './images/bt/bt-f1-tyt-13.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-14',
    name: 'Floor 1 – TYT 14',
    caption: 'BT – Floor 1 – TYT 14',
    panorama: './images/bt/bt-f1-tyt-14.jpg',
    thumbnail: './images/bt/bt-f1-tyt-14.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-15',
    name: 'Floor 1 – TYT 15',
    caption: 'BT – Floor 1 – TYT 15',
    panorama: './images/bt/bt-f1-tyt-15.jpg',
    thumbnail: './images/bt/bt-f1-tyt-15.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
  {
    id: 'bt-f1-tyt-16',
    name: 'Floor 1 – TYT 16',
    caption: 'BT – Floor 1 – TYT 16',
    panorama: './images/bt/bt-f1-tyt-16.jpg',
    thumbnail: './images/bt/bt-f1-tyt-16.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [],
    markers: [],
    data: {
      floor: 'f1',
      tags: ['tyt'],
    },
  },
];
