// ── locations/bt/f2-reading.js ─────────────────────────────────────
export default [
  {
    id: 'bt-f2-reading-1',
    name: 'Floor 2 – Reading 1',
    caption: 'BT – Floor 2 – Reading 1',
    panorama: './images/bt/f2-reading/bt-f2-reading-1.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-1.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-2',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 2',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-2',
    name: 'Floor 2 – Reading 2',
    caption: 'BT – Floor 2 – Reading 2',
    panorama: './images/bt/f2-reading/bt-f2-reading-2.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-2.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-1',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 1',
        },
        {
          nodeId: 'bt-f2-reading-3',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 3',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-3',
    name: 'Floor 2 – Reading 3',
    caption: 'BT – Floor 2 – Reading 3',
    panorama: './images/bt/f2-reading/bt-f2-reading-3.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-3.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-2',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 2',
        },
        {
          nodeId: 'bt-f2-reading-4',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 4',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-4',
    name: 'Floor 2 – Reading 4',
    caption: 'BT – Floor 2 – Reading 4',
    panorama: './images/bt/f2-reading/bt-f2-reading-4.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-4.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-3',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 3',
        },
        {
          nodeId: 'bt-f2-reading-5',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 5',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-5',
    name: 'Floor 2 – Reading 5',
    caption: 'BT – Floor 2 – Reading 5',
    panorama: './images/bt/f2-reading/bt-f2-reading-5.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-5.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-4',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 4',
        },
        {
          nodeId: 'bt-f2-reading-6',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 6',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-6',
    name: 'Floor 2 – Reading 6',
    caption: 'BT – Floor 2 – Reading 6',
    panorama: './images/bt/f2-reading/bt-f2-reading-6.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-6.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-5',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 5',
        },
        {
          nodeId: 'bt-f2-reading-7',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 7',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-7',
    name: 'Floor 2 – Reading 7',
    caption: 'BT – Floor 2 – Reading 7',
    panorama: './images/bt/f2-reading/bt-f2-reading-7.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-7.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-6',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 6',
        },
        {
          nodeId: 'bt-f2-reading-8',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 8',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-8',
    name: 'Floor 2 – Reading 8',
    caption: 'BT – Floor 2 – Reading 8',
    panorama: './images/bt/f2-reading/bt-f2-reading-8.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-8.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-7',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 7',
        },
        {
          nodeId: 'bt-f2-reading-9',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 9',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-9',
    name: 'Floor 2 – Reading 9',
    caption: 'BT – Floor 2 – Reading 9',
    panorama: './images/bt/f2-reading/bt-f2-reading-9.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-9.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-8',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 8',
        },
        {
          nodeId: 'bt-f2-reading-10',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 10',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-10',
    name: 'Floor 2 – Reading 10',
    caption: 'BT – Floor 2 – Reading 10',
    panorama: './images/bt/f2-reading/bt-f2-reading-10.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-10.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-9',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 9',
        },
        {
          nodeId: 'bt-f2-reading-11',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 11',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-11',
    name: 'Floor 2 – Reading 11',
    caption: 'BT – Floor 2 – Reading 11',
    panorama: './images/bt/f2-reading/bt-f2-reading-11.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-11.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-10',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 10',
        },
        {
          nodeId: 'bt-f2-reading-12',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 12',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-12',
    name: 'Floor 2 – Reading 12',
    caption: 'BT – Floor 2 – Reading 12',
    panorama: './images/bt/f2-reading/bt-f2-reading-12.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-12.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-11',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 11',
        },
        {
          nodeId: 'bt-f2-reading-13',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 13',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-13',
    name: 'Floor 2 – Reading 13',
    caption: 'BT – Floor 2 – Reading 13',
    panorama: './images/bt/f2-reading/bt-f2-reading-13.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-13.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-12',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 12',
        },
        {
          nodeId: 'bt-f2-reading-14',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 14',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-14',
    name: 'Floor 2 – Reading 14',
    caption: 'BT – Floor 2 – Reading 14',
    panorama: './images/bt/f2-reading/bt-f2-reading-14.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-14.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-13',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 13',
        },
        {
          nodeId: 'bt-f2-reading-15',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 15',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-15',
    name: 'Floor 2 – Reading 15',
    caption: 'BT – Floor 2 – Reading 15',
    panorama: './images/bt/f2-reading/bt-f2-reading-15.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-15.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-14',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 14',
        },
        {
          nodeId: 'bt-f2-reading-16',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 16',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-16',
    name: 'Floor 2 – Reading 16',
    caption: 'BT – Floor 2 – Reading 16',
    panorama: './images/bt/f2-reading/bt-f2-reading-16.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-16.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-15',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 15',
        },
        {
          nodeId: 'bt-f2-reading-17',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 17',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-17',
    name: 'Floor 2 – Reading 17',
    caption: 'BT – Floor 2 – Reading 17',
    panorama: './images/bt/f2-reading/bt-f2-reading-17.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-17.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-16',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 16',
        },
        {
          nodeId: 'bt-f2-reading-18',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 18',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-18',
    name: 'Floor 2 – Reading 18',
    caption: 'BT – Floor 2 – Reading 18',
    panorama: './images/bt/f2-reading/bt-f2-reading-18.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-18.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-17',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 17',
        },
        {
          nodeId: 'bt-f2-reading-19',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 19',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-19',
    name: 'Floor 2 – Reading 19',
    caption: 'BT – Floor 2 – Reading 19',
    panorama: './images/bt/f2-reading/bt-f2-reading-19.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-19.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-18',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 18',
        },
        {
          nodeId: 'bt-f2-reading-20',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 20',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-20',
    name: 'Floor 2 – Reading 20',
    caption: 'BT – Floor 2 – Reading 20',
    panorama: './images/bt/f2-reading/bt-f2-reading-20.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-20.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-19',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 19',
        },
        {
          nodeId: 'bt-f2-reading-21',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 21',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-21',
    name: 'Floor 2 – Reading 21',
    caption: 'BT – Floor 2 – Reading 21',
    panorama: './images/bt/f2-reading/bt-f2-reading-21.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-21.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-20',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 20',
        },
        {
          nodeId: 'bt-f2-reading-22',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 22',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-22',
    name: 'Floor 2 – Reading 22',
    caption: 'BT – Floor 2 – Reading 22',
    panorama: './images/bt/f2-reading/bt-f2-reading-22.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-22.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-21',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 21',
        },
        {
          nodeId: 'bt-f2-reading-23',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 23',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-23',
    name: 'Floor 2 – Reading 23',
    caption: 'BT – Floor 2 – Reading 23',
    panorama: './images/bt/f2-reading/bt-f2-reading-23.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-23.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-22',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 22',
        },
        {
          nodeId: 'bt-f2-reading-24',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 24',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-24',
    name: 'Floor 2 – Reading 24',
    caption: 'BT – Floor 2 – Reading 24',
    panorama: './images/bt/f2-reading/bt-f2-reading-24.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-24.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-23',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 23',
        },
        {
          nodeId: 'bt-f2-reading-25',
          position: { yaw: '358.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 25',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
    },
  },
  {
    id: 'bt-f2-reading-25',
    name: 'Floor 2 – Reading 25',
    caption: 'BT – Floor 2 – Reading 25',
    panorama: './images/bt/f2-reading/bt-f2-reading-25.jpg',
    thumbnail: './images/bt/f2-reading/bt-f2-reading-25.jpg',
    defaultYaw: '0deg',
    defaultPitch: '0deg',
    links: [
        {
          nodeId: 'bt-f2-reading-24',
          position: { yaw: '178.45deg', pitch: '-8.15deg' },
          name: 'Go to Reading 24',
        },
      ],
    markers: [],
    data: {
      floor: 'f2',
      tags: ['reading'],
      },
    },
];

